# Generated by Django 3.1.6 on 2021-12-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attach', '0002_remove_student_mdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
