# Generated by Django 3.1.6 on 2021-12-27 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attach', '0003_student_mdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='elogbook',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='attach.compdetails'),
        ),
    ]
